model_config:
  model: UNet1 #the directory to which the results are saved
  initial_filter_size: [64]
  kernel: [3]
  drop_out_rate: [0.25]
  input_size: [512, 512] #h, w
  channel: 1
  num_class: 1
  model_type: 'single' #multi_task, attention, fourier1, single
train_config:
  loss: BCE
  accuracy: dice_score
  optimizer: Radam
  lr_rate: [0.0001]
  weight_decay: [0]
  batch_size: [2]
  epochs: 100
  num_workers: 20
  use_cuda: True
dataset_config:
  train_path: '..//liver_dataset_processed_fourier//train'
  val_path: '..//liver_dataset_processed_fourier//val'
  test_path: '../liver_dataset_processed_fourier/test'
  aug_rate: [0]
  save_dir: exp1_single_task_64
  class_names: ['background','liver']
resume:
  flag: False
  path: exp2_fouirer//models//last_epoch.pt
  epoch: 10

